/**
 * Quant Overledger API
 * Quant’s Overledger API allows developers to create applications for multiple DLT’s using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AliasDetails model module.
 * @module model/AliasDetails
 * @version 2.0
 */
class AliasDetails {
    /**
     * Constructs a new <code>AliasDetails</code>.
     * Alias Details of an account
     * @alias module:model/AliasDetails
     */
    constructor() { 
        
        AliasDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AliasDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AliasDetails} obj Optional instance to populate.
     * @return {module:model/AliasDetails} The populated <code>AliasDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AliasDetails();

            if (data.hasOwnProperty('accountId')) {
                obj['accountId'] = ApiClient.convertToType(data['accountId'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('disposableAlias')) {
                obj['disposableAlias'] = ApiClient.convertToType(data['disposableAlias'], 'Boolean');
            }
            if (data.hasOwnProperty('aliasHash')) {
                obj['aliasHash'] = ApiClient.convertToType(data['aliasHash'], 'String');
            }
            if (data.hasOwnProperty('aliasType')) {
                obj['aliasType'] = ApiClient.convertToType(data['aliasType'], 'String');
            }
            if (data.hasOwnProperty('esipId')) {
                obj['esipId'] = ApiClient.convertToType(data['esipId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} accountId
 */
AliasDetails.prototype['accountId'] = undefined;

/**
 * @member {String} unit
 */
AliasDetails.prototype['unit'] = undefined;

/**
 * @member {Boolean} disposableAlias
 */
AliasDetails.prototype['disposableAlias'] = undefined;

/**
 * @member {String} aliasHash
 */
AliasDetails.prototype['aliasHash'] = undefined;

/**
 * @member {String} aliasType
 */
AliasDetails.prototype['aliasType'] = undefined;

/**
 * @member {String} esipId
 */
AliasDetails.prototype['esipId'] = undefined;






export default AliasDetails;

