/**
 * Quant Overledger API
 * Quant’s Overledger API allows developers to create applications for multiple DLT’s using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Location from './Location';
import Status from './Status';
import Transaction from './Transaction';

/**
 * The ExecuteSearchTransactionResponse model module.
 * @module model/ExecuteSearchTransactionResponse
 * @version 2.0
 */
class ExecuteSearchTransactionResponse {
    /**
     * Constructs a new <code>ExecuteSearchTransactionResponse</code>.
     * @alias module:model/ExecuteSearchTransactionResponse
     */
    constructor() { 
        
        ExecuteSearchTransactionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExecuteSearchTransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExecuteSearchTransactionResponse} obj Optional instance to populate.
     * @return {module:model/ExecuteSearchTransactionResponse} The populated <code>ExecuteSearchTransactionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExecuteSearchTransactionResponse();

            if (data.hasOwnProperty('location')) {
                obj['location'] = Location.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = Transaction.constructFromObject(data['transaction']);
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('extraFields')) {
                obj['extraFields'] = ApiClient.convertToType(data['extraFields'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Location} location
 */
ExecuteSearchTransactionResponse.prototype['location'] = undefined;

/**
 * The type of the transaction object returned
 * @member {String} type
 */
ExecuteSearchTransactionResponse.prototype['type'] = undefined;

/**
 * @member {module:model/Transaction} transaction
 */
ExecuteSearchTransactionResponse.prototype['transaction'] = undefined;

/**
 * The unix time to read the object from
 * @member {String} timestamp
 */
ExecuteSearchTransactionResponse.prototype['timestamp'] = undefined;

/**
 * @member {module:model/Status} status
 */
ExecuteSearchTransactionResponse.prototype['status'] = undefined;

/**
 * @member {Object} extraFields
 */
ExecuteSearchTransactionResponse.prototype['extraFields'] = undefined;






export default ExecuteSearchTransactionResponse;

