/**
 * Quant Overledger API
 * Quant's Overledger API allows developers to create applications for multiple DLT's using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SmartContractInputParameterSchema from './SmartContractInputParameterSchema';
import SmartContractOutputParameterSchema from './SmartContractOutputParameterSchema';

/**
 * The SmartContractSearchFunctionSchema model module.
 * @module model/SmartContractSearchFunctionSchema
 * @version 2.0
 */
class SmartContractSearchFunctionSchema {
    /**
     * Constructs a new <code>SmartContractSearchFunctionSchema</code>.
     * @alias module:model/SmartContractSearchFunctionSchema
     */
    constructor() { 
        
        SmartContractSearchFunctionSchema.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SmartContractSearchFunctionSchema</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SmartContractSearchFunctionSchema} obj Optional instance to populate.
     * @return {module:model/SmartContractSearchFunctionSchema} The populated <code>SmartContractSearchFunctionSchema</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SmartContractSearchFunctionSchema();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('inputParameters')) {
                obj['inputParameters'] = ApiClient.convertToType(data['inputParameters'], [SmartContractInputParameterSchema]);
            }
            if (data.hasOwnProperty('outputParameters')) {
                obj['outputParameters'] = ApiClient.convertToType(data['outputParameters'], [SmartContractOutputParameterSchema]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
SmartContractSearchFunctionSchema.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/SmartContractInputParameterSchema>} inputParameters
 */
SmartContractSearchFunctionSchema.prototype['inputParameters'] = undefined;

/**
 * @member {Array.<module:model/SmartContractOutputParameterSchema>} outputParameters
 */
SmartContractSearchFunctionSchema.prototype['outputParameters'] = undefined;






export default SmartContractSearchFunctionSchema;

