{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import QuantOverledger.Model
import QuantOverledger.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AccountDetails)
      propMimeEq MimeJSON (Proxy :: Proxy AddSecondaryAccountRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AdditionalOwner)
      propMimeEq MimeJSON (Proxy :: Proxy AdditionalOwnerRemoveSecondarySchema)
      propMimeEq MimeJSON (Proxy :: Proxy AddressBalanceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy AddressMonitoringDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AddressMonitoringRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AddressMonitoringResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AliasDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ApproveRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AutoExecSearchAddressSequenceResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AutoExecuteSearchAddressBalanceResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AutoExecuteSearchBlockResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AutoExecuteSearchUTXOResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Beneficiary)
      propMimeEq MimeJSON (Proxy :: Proxy BeneficiaryMintSchemaQrc20)
      propMimeEq MimeJSON (Proxy :: Proxy BeneficiaryMintSchemaQrc721)
      propMimeEq MimeJSON (Proxy :: Proxy Block)
      propMimeEq MimeJSON (Proxy :: Proxy BlockHash)
      propMimeEq MimeJSON (Proxy :: Proxy BlockSize)
      propMimeEq MimeJSON (Proxy :: Proxy Burn)
      propMimeEq MimeJSON (Proxy :: Proxy BurnRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy BurnRequestDetailsSchemaQrc721)
      propMimeEq MimeJSON (Proxy :: Proxy BurnSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Collector)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmartContractMonitoringSchema)
      propMimeEq MimeJSON (Proxy :: Proxy CreateWebhookSubscriptionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy CreateWebhookSubscriptionResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Creator)
      propMimeEq MimeJSON (Proxy :: Proxy CreatorMintSchema)
      propMimeEq MimeJSON (Proxy :: Proxy CreditRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy DeleteResourceMonitoringAddressSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Destination)
      propMimeEq MimeJSON (Proxy :: Proxy DestinationPaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy DestinationTransferSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Erc20DTO)
      propMimeEq MimeJSON (Proxy :: Proxy Error)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorList)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorResponseMessage)
      propMimeEq MimeJSON (Proxy :: Proxy EventSubscriptionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy EventSubscriptionResponseDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchBalanceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchBlockResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchSequenceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchUTXOResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchUTXOResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSmartContractReadResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteTransactionRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExtraFields)
      propMimeEq MimeJSON (Proxy :: Proxy Fee)
      propMimeEq MimeJSON (Proxy :: Proxy Function)
      propMimeEq MimeJSON (Proxy :: Proxy FunctionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy FungibleTokenResponseDTO)
      propMimeEq MimeJSON (Proxy :: Proxy InternalServerErrorSchema)
      propMimeEq MimeJSON (Proxy :: Proxy LinkedBlocks)
      propMimeEq MimeJSON (Proxy :: Proxy ListWebhookSubscriptionResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Location)
      propMimeEq MimeJSON (Proxy :: Proxy LocationDTO)
      propMimeEq MimeJSON (Proxy :: Proxy LockDetails)
      propMimeEq MimeJSON (Proxy :: Proxy Mandate)
      propMimeEq MimeJSON (Proxy :: Proxy Mint)
      propMimeEq MimeJSON (Proxy :: Proxy MintRequestDetailsSchemaQrc20)
      propMimeEq MimeJSON (Proxy :: Proxy MintRequestDetailsSchemaQrc721)
      propMimeEq MimeJSON (Proxy :: Proxy MintSchemaQrc20)
      propMimeEq MimeJSON (Proxy :: Proxy MintSchemaQrc721)
      propMimeEq MimeJSON (Proxy :: Proxy MonitorSmartContractEventParam)
      propMimeEq MimeJSON (Proxy :: Proxy MonitorSmartContractRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy NonFungibleTokenDTO)
      propMimeEq MimeJSON (Proxy :: Proxy NonFungibleTokenResponse)
      propMimeEq MimeJSON (Proxy :: Proxy Origin)
      propMimeEq MimeJSON (Proxy :: Proxy OriginPaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy OriginTransferSchema)
      propMimeEq MimeJSON (Proxy :: Proxy OverledgerTransactionResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Owner)
      propMimeEq MimeJSON (Proxy :: Proxy OwnerBurnSchema)
      propMimeEq MimeJSON (Proxy :: Proxy OwnerRemoveSecondarySchema)
      propMimeEq MimeJSON (Proxy :: Proxy Pagination)
      propMimeEq MimeJSON (Proxy :: Proxy Parameter)
      propMimeEq MimeJSON (Proxy :: Proxy Payee)
      propMimeEq MimeJSON (Proxy :: Proxy PayeeCreditSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Payer)
      propMimeEq MimeJSON (Proxy :: Proxy PayerCreditSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Payment)
      propMimeEq MimeJSON (Proxy :: Proxy PaymentRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareAddSecondaryAccountRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareAndExecuteBalanceDetails)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareAndExecuteOverledgerErrorResponse)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareAndExecuteSearchAddressBalanceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareAndExecuteTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareApproveDebitTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareBurnTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareBurnTransactionRequestSchemaQrc721)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareCreditTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareMintTransactionRequestSchemaQrc20)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareMintTransactionRequestSchemaQrc721)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareNativeTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PreparePaymentTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareRemoveSecondaryAccountTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareRequest)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareRequestDetails)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareSearchResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareSearchSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareSearchSmartContractRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareTransactionSmartContractInvokeRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareTransferTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadAccountBalanceRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadApprovedAccountAllowanceRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadApprovedAccountRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadApprovedAccountRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadBalanceRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadBalanceRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadContractOwnerRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadContractOwnerRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadTokenOwnerRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ReadTokenOwnerRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Receiver)
      propMimeEq MimeJSON (Proxy :: Proxy RemoveSecondaryAccountDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoredAddressDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringAddressDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringAddressSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringSmartContractEventDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringSubscription)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringSubscriptionDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ScriptPubKey)
      propMimeEq MimeJSON (Proxy :: Proxy SecondaryAccountAdditionalOwnerSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SecondaryAccountOwnerSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Sender)
      propMimeEq MimeJSON (Proxy :: Proxy SignerAccount)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContract)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractDestinationSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractEventHistory)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractFunctionSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractInputParameterSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractInvokeRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractMonitoringDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractMonitoringSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractOutputParameterSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractPaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractReadFunctionSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractReadSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractRequestDetailsOrigin)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchDestinationSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchFunctionSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchRequestDetails)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractTag)
      propMimeEq MimeJSON (Proxy :: Proxy Status)
      propMimeEq MimeJSON (Proxy :: Proxy StatusUpdateMonitoringRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy StatusUpdateSchema)
      propMimeEq MimeJSON (Proxy :: Proxy TierFunctionDTO)
      propMimeEq MimeJSON (Proxy :: Proxy TokenReadQRC20Response)
      propMimeEq MimeJSON (Proxy :: Proxy TokenReadQRC721Response)
      propMimeEq MimeJSON (Proxy :: Proxy TokenReadResponseDetails)
      propMimeEq MimeJSON (Proxy :: Proxy Transaction)
      propMimeEq MimeJSON (Proxy :: Proxy Transfer)
      propMimeEq MimeJSON (Proxy :: Proxy TransferRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy TransferSchema)
      propMimeEq MimeJSON (Proxy :: Proxy UTXODestination)
      propMimeEq MimeJSON (Proxy :: Proxy UTXONativeData)
      propMimeEq MimeJSON (Proxy :: Proxy UTXOSmartContract)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateAddressMonitoringSchema)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateWebhookSubscriptionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Vout)
      propMimeEq MimeJSON (Proxy :: Proxy WebhookStatusUpdateSchema)
      propMimeEq MimeJSON (Proxy :: Proxy WebhookSubscriptionDetails)
      propMimeEq MimeJSON (Proxy :: Proxy WebhookSubscriptionDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy WebhookSubscriptionStatusUpdateResponse)
      
