{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import QuantOverledger.Model
import QuantOverledger.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AddressBalanceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy AddressMonitoringDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AddressMonitoringRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy AddressMonitoringResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Block)
      propMimeEq MimeJSON (Proxy :: Proxy BlockHash)
      propMimeEq MimeJSON (Proxy :: Proxy BlockSize)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSmartContractMonitoringSchema)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSubscriptionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy CreateSubscriptionResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy DeleteResourceMonitoringAddressSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Destination)
      propMimeEq MimeJSON (Proxy :: Proxy DestinationPaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy DestinationTransferSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Error)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ErrorList)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchBalanceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchBlockResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchSequenceResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSearchUTXOResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteSmartContractReadResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteTransactionRequest)
      propMimeEq MimeJSON (Proxy :: Proxy ExecuteTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy ExtraFields)
      propMimeEq MimeJSON (Proxy :: Proxy Fee)
      propMimeEq MimeJSON (Proxy :: Proxy Function)
      propMimeEq MimeJSON (Proxy :: Proxy InternalServerErrorSchema)
      propMimeEq MimeJSON (Proxy :: Proxy LinkedBlocks)
      propMimeEq MimeJSON (Proxy :: Proxy ListSubscriptionResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Location)
      propMimeEq MimeJSON (Proxy :: Proxy MonitorSmartContractEventParam)
      propMimeEq MimeJSON (Proxy :: Proxy MonitorSmartContractRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Origin)
      propMimeEq MimeJSON (Proxy :: Proxy OriginPaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy OriginTransferSchema)
      propMimeEq MimeJSON (Proxy :: Proxy OverledgerTransactionResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Parameter)
      propMimeEq MimeJSON (Proxy :: Proxy Payment)
      propMimeEq MimeJSON (Proxy :: Proxy PaymentRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareNativeTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PreparePaymentTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareSearchResponseSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareSearchSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareSearchSmartContractRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareTransactionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareTransactionSmartContractInvokeRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy PrepareTransferTransactionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoredAddressDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringAddressDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringAddressSchema)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringSmartContractEventDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringSubscription)
      propMimeEq MimeJSON (Proxy :: Proxy ResourceMonitoringSubscriptionDetails)
      propMimeEq MimeJSON (Proxy :: Proxy ScriptPubKey)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContract)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractDestinationSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractEventHistory)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractFunctionSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractInputParameterSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractInvokeRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractMonitoringDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractMonitoringSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractOutputParameterSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractPaymentSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractReadFunctionSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractReadSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractRequestDetailsOrigin)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchDestinationSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchFunctionSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchRequestDetails)
      propMimeEq MimeJSON (Proxy :: Proxy SmartContractSearchSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Status)
      propMimeEq MimeJSON (Proxy :: Proxy StatusUpdateMonitoringRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy StatusUpdateSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SubscriptionDeletionResponse)
      propMimeEq MimeJSON (Proxy :: Proxy SubscriptionDetails)
      propMimeEq MimeJSON (Proxy :: Proxy SubscriptionDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy SubscriptionUpdateResponse)
      propMimeEq MimeJSON (Proxy :: Proxy Transaction)
      propMimeEq MimeJSON (Proxy :: Proxy Transfer)
      propMimeEq MimeJSON (Proxy :: Proxy TransferRequestDetailsSchema)
      propMimeEq MimeJSON (Proxy :: Proxy TransferSchema)
      propMimeEq MimeJSON (Proxy :: Proxy UTXODestination)
      propMimeEq MimeJSON (Proxy :: Proxy UTXONativeData)
      propMimeEq MimeJSON (Proxy :: Proxy UTXOSmartContract)
      propMimeEq MimeJSON (Proxy :: Proxy UTXOTimestampSchema)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateAddressMonitoringSchema)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateSubscriptionRequestSchema)
      propMimeEq MimeJSON (Proxy :: Proxy Vout)
      
