/*
 * Quant Overledger API
 *
 * Quant’s Overledger API allows developers to create applications for multiple DLT’s using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation  # Authentication  <!- - ReDoc-Inject: <security-definitions> - ->
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PrepareTransactionResponse
    /// </summary>
    [DataContract]
    public partial class PrepareTransactionResponse :  IEquatable<PrepareTransactionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrepareTransactionResponse" /> class.
        /// </summary>
        /// <param name="gatewayFee">gatewayFee.</param>
        /// <param name="requestId">The ID assigned to a preparation request in Overledger.</param>
        /// <param name="dltFee">dltFee.</param>
        /// <param name="nativeData">nativeData.</param>
        public PrepareTransactionResponse(Fee gatewayFee = default(Fee), string requestId = default(string), Fee dltFee = default(Fee), Object nativeData = default(Object))
        {
            this.GatewayFee = gatewayFee;
            this.RequestId = requestId;
            this.DltFee = dltFee;
            this.NativeData = nativeData;
        }

        /// <summary>
        /// Gets or Sets GatewayFee
        /// </summary>
        [DataMember(Name="gatewayFee", EmitDefaultValue=false)]
        public Fee GatewayFee { get; set; }

        /// <summary>
        /// The ID assigned to a preparation request in Overledger
        /// </summary>
        /// <value>The ID assigned to a preparation request in Overledger</value>
        [DataMember(Name="requestId", EmitDefaultValue=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or Sets DltFee
        /// </summary>
        [DataMember(Name="dltFee", EmitDefaultValue=false)]
        public Fee DltFee { get; set; }

        /// <summary>
        /// Gets or Sets NativeData
        /// </summary>
        [DataMember(Name="nativeData", EmitDefaultValue=false)]
        public Object NativeData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PrepareTransactionResponse {\n");
            sb.Append("  GatewayFee: ").Append(GatewayFee).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  DltFee: ").Append(DltFee).Append("\n");
            sb.Append("  NativeData: ").Append(NativeData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PrepareTransactionResponse);
        }

        /// <summary>
        /// Returns true if PrepareTransactionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PrepareTransactionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrepareTransactionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GatewayFee == input.GatewayFee ||
                    (this.GatewayFee != null &&
                    this.GatewayFee.Equals(input.GatewayFee))
                ) && 
                (
                    this.RequestId == input.RequestId ||
                    (this.RequestId != null &&
                    this.RequestId.Equals(input.RequestId))
                ) && 
                (
                    this.DltFee == input.DltFee ||
                    (this.DltFee != null &&
                    this.DltFee.Equals(input.DltFee))
                ) && 
                (
                    this.NativeData == input.NativeData ||
                    (this.NativeData != null &&
                    this.NativeData.Equals(input.NativeData))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GatewayFee != null)
                    hashCode = hashCode * 59 + this.GatewayFee.GetHashCode();
                if (this.RequestId != null)
                    hashCode = hashCode * 59 + this.RequestId.GetHashCode();
                if (this.DltFee != null)
                    hashCode = hashCode * 59 + this.DltFee.GetHashCode();
                if (this.NativeData != null)
                    hashCode = hashCode * 59 + this.NativeData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RequestId (string) maxLength
            if(this.RequestId != null && this.RequestId.Length > 36)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RequestId, length must be less than 36.", new [] { "RequestId" });
            }

            // RequestId (string) minLength
            if(this.RequestId != null && this.RequestId.Length < 0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RequestId, length must be greater than 0.", new [] { "RequestId" });
            }

            // RequestId (string) pattern
            Regex regexRequestId = new Regex(@"^[A-Za-z0-9-]{1,36}$", RegexOptions.CultureInvariant);
            if (false == regexRequestId.Match(this.RequestId).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RequestId, must match a pattern of " + regexRequestId, new [] { "RequestId" });
            }

            yield break;
        }
    }

}
