<?php
/**
 * Status
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Quant Overledger API
 *
 * Quant's Overledger API allows developers to create applications for multiple DLT's using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Status Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class Status implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Status';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'description' => 'string',
        'message' => 'string',
        'value' => 'string',
        'timestamp' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'description' => null,
        'message' => null,
        'value' => null,
        'timestamp' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'description' => 'description',
        'message' => 'message',
        'value' => 'value',
        'timestamp' => 'timestamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'description' => 'setDescription',
        'message' => 'setMessage',
        'value' => 'setValue',
        'timestamp' => 'setTimestamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'description' => 'getDescription',
        'message' => 'getMessage',
        'value' => 'getValue',
        'timestamp' => 'getTimestamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = $data['code'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['message'] = $data['message'] ?? null;
        $this->container['value'] = $data['value'] ?? null;
        $this->container['timestamp'] = $data['timestamp'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) > 30)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be smaller than or equal to 30.";
        }

        if (!is_null($this->container['code']) && (mb_strlen($this->container['code']) < 0)) {
            $invalidProperties[] = "invalid value for 'code', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['code']) && !preg_match("/^[a-zA-Z_0-9 ]{1,30}\"/", $this->container['code'])) {
            $invalidProperties[] = "invalid value for 'code', must be conform to the pattern /^[a-zA-Z_0-9 ]{1,30}\"/.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 400)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 400.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) < 0)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['description']) && !preg_match("/^[a-zA-Z_0-9.,\\-() ]{1,400}/", $this->container['description'])) {
            $invalidProperties[] = "invalid value for 'description', must be conform to the pattern /^[a-zA-Z_0-9.,\\-() ]{1,400}/.";
        }

        if (!is_null($this->container['message']) && (mb_strlen($this->container['message']) > 400)) {
            $invalidProperties[] = "invalid value for 'message', the character length must be smaller than or equal to 400.";
        }

        if (!is_null($this->container['message']) && (mb_strlen($this->container['message']) < 0)) {
            $invalidProperties[] = "invalid value for 'message', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['message']) && !preg_match("/^[a-zA-Z_0-9.,\\-() ]{1,400}/", $this->container['message'])) {
            $invalidProperties[] = "invalid value for 'message', must be conform to the pattern /^[a-zA-Z_0-9.,\\-() ]{1,400}/.";
        }

        if (!is_null($this->container['value']) && (mb_strlen($this->container['value']) > 50)) {
            $invalidProperties[] = "invalid value for 'value', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['value']) && (mb_strlen($this->container['value']) < 0)) {
            $invalidProperties[] = "invalid value for 'value', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['value']) && !preg_match("/^[a-zA-Z0-9-_ ]{1,50}$/", $this->container['value'])) {
            $invalidProperties[] = "invalid value for 'value', must be conform to the pattern /^[a-zA-Z0-9-_ ]{1,50}$/.";
        }

        if (!is_null($this->container['timestamp']) && (mb_strlen($this->container['timestamp']) > 50)) {
            $invalidProperties[] = "invalid value for 'timestamp', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['timestamp']) && (mb_strlen($this->container['timestamp']) < 0)) {
            $invalidProperties[] = "invalid value for 'timestamp', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['timestamp']) && !preg_match("/^[a-zA-Z_0-9.,:\\- ]{1,50}/", $this->container['timestamp'])) {
            $invalidProperties[] = "invalid value for 'timestamp', must be conform to the pattern /^[a-zA-Z_0-9.,:\\- ]{1,50}/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code The code of an object
     *
     * @return self
     */
    public function setCode($code)
    {
        if (!is_null($code) && (mb_strlen($code) > 30)) {
            throw new \InvalidArgumentException('invalid length for $code when calling Status., must be smaller than or equal to 30.');
        }
        if (!is_null($code) && (mb_strlen($code) < 0)) {
            throw new \InvalidArgumentException('invalid length for $code when calling Status., must be bigger than or equal to 0.');
        }
        if (!is_null($code) && (!preg_match("/^[a-zA-Z_0-9 ]{1,30}\"/", $code))) {
            throw new \InvalidArgumentException("invalid value for $code when calling Status., must conform to the pattern /^[a-zA-Z_0-9 ]{1,30}\"/.");
        }

        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of an object
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (!is_null($description) && (mb_strlen($description) > 400)) {
            throw new \InvalidArgumentException('invalid length for $description when calling Status., must be smaller than or equal to 400.');
        }
        if (!is_null($description) && (mb_strlen($description) < 0)) {
            throw new \InvalidArgumentException('invalid length for $description when calling Status., must be bigger than or equal to 0.');
        }
        if (!is_null($description) && (!preg_match("/^[a-zA-Z_0-9.,\\-() ]{1,400}/", $description))) {
            throw new \InvalidArgumentException("invalid value for $description when calling Status., must conform to the pattern /^[a-zA-Z_0-9.,\\-() ]{1,400}/.");
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message The message of an object
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (!is_null($message) && (mb_strlen($message) > 400)) {
            throw new \InvalidArgumentException('invalid length for $message when calling Status., must be smaller than or equal to 400.');
        }
        if (!is_null($message) && (mb_strlen($message) < 0)) {
            throw new \InvalidArgumentException('invalid length for $message when calling Status., must be bigger than or equal to 0.');
        }
        if (!is_null($message) && (!preg_match("/^[a-zA-Z_0-9.,\\-() ]{1,400}/", $message))) {
            throw new \InvalidArgumentException("invalid value for $message when calling Status., must conform to the pattern /^[a-zA-Z_0-9.,\\-() ]{1,400}/.");
        }

        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string|null $value The value of an object
     *
     * @return self
     */
    public function setValue($value)
    {
        if (!is_null($value) && (mb_strlen($value) > 50)) {
            throw new \InvalidArgumentException('invalid length for $value when calling Status., must be smaller than or equal to 50.');
        }
        if (!is_null($value) && (mb_strlen($value) < 0)) {
            throw new \InvalidArgumentException('invalid length for $value when calling Status., must be bigger than or equal to 0.');
        }
        if (!is_null($value) && (!preg_match("/^[a-zA-Z0-9-_ ]{1,50}$/", $value))) {
            throw new \InvalidArgumentException("invalid value for $value when calling Status., must conform to the pattern /^[a-zA-Z0-9-_ ]{1,50}$/.");
        }

        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return string|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param string|null $timestamp timestamp
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (!is_null($timestamp) && (mb_strlen($timestamp) > 50)) {
            throw new \InvalidArgumentException('invalid length for $timestamp when calling Status., must be smaller than or equal to 50.');
        }
        if (!is_null($timestamp) && (mb_strlen($timestamp) < 0)) {
            throw new \InvalidArgumentException('invalid length for $timestamp when calling Status., must be bigger than or equal to 0.');
        }
        if (!is_null($timestamp) && (!preg_match("/^[a-zA-Z_0-9.,:\\- ]{1,50}/", $timestamp))) {
            throw new \InvalidArgumentException("invalid value for $timestamp when calling Status., must conform to the pattern /^[a-zA-Z_0-9.,:\\- ]{1,50}/.");
        }

        $this->container['timestamp'] = $timestamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


