/*
 * Quant Overledger API
 *
 * Quant’s Overledger API allows developers to create applications for multiple DLT’s using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AliasDetails : Alias Details of an account



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AliasDetails {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "disposableAlias", skip_serializing_if = "Option::is_none")]
    pub disposable_alias: Option<bool>,
    #[serde(rename = "aliasHash", skip_serializing_if = "Option::is_none")]
    pub alias_hash: Option<String>,
    #[serde(rename = "aliasType", skip_serializing_if = "Option::is_none")]
    pub alias_type: Option<String>,
    #[serde(rename = "esipId", skip_serializing_if = "Option::is_none")]
    pub esip_id: Option<String>,
}

impl AliasDetails {
    /// Alias Details of an account
    pub fn new() -> AliasDetails {
        AliasDetails {
            account_id: None,
            unit: None,
            disposable_alias: None,
            alias_hash: None,
            alias_type: None,
            esip_id: None,
        }
    }
}


