=begin comment

Quant Overledger API

Quant's Overledger API allows developers to create applications for multiple DLT's using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::MonitorAResourceApi');

my $api = WWW::OpenAPIClient::MonitorAResourceApi->new();
isa_ok($api, 'WWW::OpenAPIClient::MonitorAResourceApi');

#
# resource_monitoring_address test
#
# uncomment below and update the test
#my $resource_monitoring_address_authorization = undef; # replace NULL with a proper value
#my $resource_monitoring_address_address_monitoring_request_schema = undef; # replace NULL with a proper value
#my $resource_monitoring_address_result = $api->resource_monitoring_address(authorization => $resource_monitoring_address_authorization, address_monitoring_request_schema => $resource_monitoring_address_address_monitoring_request_schema);

#
# track_and_subscribe_event test
#
# uncomment below and update the test
#my $track_and_subscribe_event_authorization = undef; # replace NULL with a proper value
#my $track_and_subscribe_event_monitor_smart_contract_request_schema = undef; # replace NULL with a proper value
#my $track_and_subscribe_event_result = $api->track_and_subscribe_event(authorization => $track_and_subscribe_event_authorization, monitor_smart_contract_request_schema => $track_and_subscribe_event_monitor_smart_contract_request_schema);

