/*
 * Quant Overledger API
 *
 * Quant's Overledger API allows developers to create applications for multiple DLT's using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PayeeCreditSchema : Who are the payees of this transaction



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PayeeCreditSchema {
    #[serde(rename = "payment", skip_serializing_if = "Option::is_none")]
    pub payment: Option<Box<crate::models::PaymentSchema>>,
    /// The unique identifiers of the payees
    #[serde(rename = "payeeId", skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<String>,
}

impl PayeeCreditSchema {
    /// Who are the payees of this transaction
    pub fn new() -> PayeeCreditSchema {
        PayeeCreditSchema {
            payment: None,
            payee_id: None,
        }
    }
}


