/**
 * Quant Overledger API
 * Quant’s Overledger API allows developers to create applications for multiple DLT’s using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebhookSubscriptionDetails from './WebhookSubscriptionDetails';

/**
 * The WebhookSubscriptionStatusUpdateResponse model module.
 * @module model/WebhookSubscriptionStatusUpdateResponse
 * @version 2.0
 */
class WebhookSubscriptionStatusUpdateResponse {
    /**
     * Constructs a new <code>WebhookSubscriptionStatusUpdateResponse</code>.
     * @alias module:model/WebhookSubscriptionStatusUpdateResponse
     */
    constructor() { 
        
        WebhookSubscriptionStatusUpdateResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebhookSubscriptionStatusUpdateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookSubscriptionStatusUpdateResponse} obj Optional instance to populate.
     * @return {module:model/WebhookSubscriptionStatusUpdateResponse} The populated <code>WebhookSubscriptionStatusUpdateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookSubscriptionStatusUpdateResponse();

            if (data.hasOwnProperty('subscriptionDetails')) {
                obj['subscriptionDetails'] = WebhookSubscriptionDetails.constructFromObject(data['subscriptionDetails']);
            }
            if (data.hasOwnProperty('callbackUrl')) {
                obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/WebhookSubscriptionDetails} subscriptionDetails
 */
WebhookSubscriptionStatusUpdateResponse.prototype['subscriptionDetails'] = undefined;

/**
 * @member {String} callbackUrl
 */
WebhookSubscriptionStatusUpdateResponse.prototype['callbackUrl'] = undefined;

/**
 * @member {String} subscriptionId
 */
WebhookSubscriptionStatusUpdateResponse.prototype['subscriptionId'] = undefined;

/**
 * @member {String} type
 */
WebhookSubscriptionStatusUpdateResponse.prototype['type'] = undefined;






export default WebhookSubscriptionStatusUpdateResponse;

