=begin
#Quant Overledger API

#Quant’s Overledger API allows developers to create applications for multiple DLT’s using a single standard set of operations and data structures.In order to maintain the security of private keys, most operations have two steps – prepare and execute. The prepare step is the point at which all arguments are specified and standardised payloads are sent. Overledger converts this standard payload into a DLT-specific transaction object. In the execute step, the SDK signs the transaction object that Overledger created and submits it to Overledger to perform the operation

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'date'
require 'time'

module OpenapiClient
  class OverledgerTransactionResponseSchema
    attr_accessor :client_id

    attr_accessor :request_id

    attr_accessor :overledger_transaction_id

    attr_accessor :location

    attr_accessor :transaction_history

    attr_accessor :type

    attr_accessor :transaction_id

    attr_accessor :status

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'client_id' => :'clientId',
        :'request_id' => :'requestId',
        :'overledger_transaction_id' => :'overledgerTransactionId',
        :'location' => :'location',
        :'transaction_history' => :'transactionHistory',
        :'type' => :'type',
        :'transaction_id' => :'transactionId',
        :'status' => :'status'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'client_id' => :'String',
        :'request_id' => :'String',
        :'overledger_transaction_id' => :'String',
        :'location' => :'Location',
        :'transaction_history' => :'Array<Status>',
        :'type' => :'String',
        :'transaction_id' => :'String',
        :'status' => :'Status'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::OverledgerTransactionResponseSchema` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::OverledgerTransactionResponseSchema`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'client_id')
        self.client_id = attributes[:'client_id']
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      end

      if attributes.key?(:'overledger_transaction_id')
        self.overledger_transaction_id = attributes[:'overledger_transaction_id']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'transaction_history')
        if (value = attributes[:'transaction_history']).is_a?(Array)
          self.transaction_history = value
        end
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'transaction_id')
        self.transaction_id = attributes[:'transaction_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@client_id.nil? && @client_id.to_s.length > 40
        invalid_properties.push('invalid value for "client_id", the character length must be smaller than or equal to 40.')
      end

      if !@client_id.nil? && @client_id.to_s.length < 0
        invalid_properties.push('invalid value for "client_id", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9]{1,40}$/)
      if !@client_id.nil? && @client_id !~ pattern
        invalid_properties.push("invalid value for \"client_id\", must conform to the pattern #{pattern}.")
      end

      if !@request_id.nil? && @request_id.to_s.length > 36
        invalid_properties.push('invalid value for "request_id", the character length must be smaller than or equal to 36.')
      end

      if !@request_id.nil? && @request_id.to_s.length < 0
        invalid_properties.push('invalid value for "request_id", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/^[A-Za-z0-9-]{1,36}$/)
      if !@request_id.nil? && @request_id !~ pattern
        invalid_properties.push("invalid value for \"request_id\", must conform to the pattern #{pattern}.")
      end

      if !@overledger_transaction_id.nil? && @overledger_transaction_id.to_s.length > 36
        invalid_properties.push('invalid value for "overledger_transaction_id", the character length must be smaller than or equal to 36.')
      end

      if !@overledger_transaction_id.nil? && @overledger_transaction_id.to_s.length < 0
        invalid_properties.push('invalid value for "overledger_transaction_id", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9\-]{1,36}$/)
      if !@overledger_transaction_id.nil? && @overledger_transaction_id !~ pattern
        invalid_properties.push("invalid value for \"overledger_transaction_id\", must conform to the pattern #{pattern}.")
      end

      if !@type.nil? && @type.to_s.length > 50
        invalid_properties.push('invalid value for "type", the character length must be smaller than or equal to 50.')
      end

      if !@type.nil? && @type.to_s.length < 0
        invalid_properties.push('invalid value for "type", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9-_ ]{1,50}$/)
      if !@type.nil? && @type !~ pattern
        invalid_properties.push("invalid value for \"type\", must conform to the pattern #{pattern}.")
      end

      if !@transaction_id.nil? && @transaction_id.to_s.length > 100
        invalid_properties.push('invalid value for "transaction_id", the character length must be smaller than or equal to 100.')
      end

      if !@transaction_id.nil? && @transaction_id.to_s.length < 0
        invalid_properties.push('invalid value for "transaction_id", the character length must be great than or equal to 0.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9-]{1,100}$/)
      if !@transaction_id.nil? && @transaction_id !~ pattern
        invalid_properties.push("invalid value for \"transaction_id\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@client_id.nil? && @client_id.to_s.length > 40
      return false if !@client_id.nil? && @client_id.to_s.length < 0
      return false if !@client_id.nil? && @client_id !~ Regexp.new(/^[a-zA-Z0-9]{1,40}$/)
      return false if !@request_id.nil? && @request_id.to_s.length > 36
      return false if !@request_id.nil? && @request_id.to_s.length < 0
      return false if !@request_id.nil? && @request_id !~ Regexp.new(/^[A-Za-z0-9-]{1,36}$/)
      return false if !@overledger_transaction_id.nil? && @overledger_transaction_id.to_s.length > 36
      return false if !@overledger_transaction_id.nil? && @overledger_transaction_id.to_s.length < 0
      return false if !@overledger_transaction_id.nil? && @overledger_transaction_id !~ Regexp.new(/^[a-zA-Z0-9\-]{1,36}$/)
      return false if !@type.nil? && @type.to_s.length > 50
      return false if !@type.nil? && @type.to_s.length < 0
      return false if !@type.nil? && @type !~ Regexp.new(/^[a-zA-Z0-9-_ ]{1,50}$/)
      return false if !@transaction_id.nil? && @transaction_id.to_s.length > 100
      return false if !@transaction_id.nil? && @transaction_id.to_s.length < 0
      return false if !@transaction_id.nil? && @transaction_id !~ Regexp.new(/^[a-zA-Z0-9-]{1,100}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] client_id Value to be assigned
    def client_id=(client_id)
      if !client_id.nil? && client_id.to_s.length > 40
        fail ArgumentError, 'invalid value for "client_id", the character length must be smaller than or equal to 40.'
      end

      if !client_id.nil? && client_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "client_id", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9]{1,40}$/)
      if !client_id.nil? && client_id !~ pattern
        fail ArgumentError, "invalid value for \"client_id\", must conform to the pattern #{pattern}."
      end

      @client_id = client_id
    end

    # Custom attribute writer method with validation
    # @param [Object] request_id Value to be assigned
    def request_id=(request_id)
      if !request_id.nil? && request_id.to_s.length > 36
        fail ArgumentError, 'invalid value for "request_id", the character length must be smaller than or equal to 36.'
      end

      if !request_id.nil? && request_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "request_id", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/^[A-Za-z0-9-]{1,36}$/)
      if !request_id.nil? && request_id !~ pattern
        fail ArgumentError, "invalid value for \"request_id\", must conform to the pattern #{pattern}."
      end

      @request_id = request_id
    end

    # Custom attribute writer method with validation
    # @param [Object] overledger_transaction_id Value to be assigned
    def overledger_transaction_id=(overledger_transaction_id)
      if !overledger_transaction_id.nil? && overledger_transaction_id.to_s.length > 36
        fail ArgumentError, 'invalid value for "overledger_transaction_id", the character length must be smaller than or equal to 36.'
      end

      if !overledger_transaction_id.nil? && overledger_transaction_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "overledger_transaction_id", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9\-]{1,36}$/)
      if !overledger_transaction_id.nil? && overledger_transaction_id !~ pattern
        fail ArgumentError, "invalid value for \"overledger_transaction_id\", must conform to the pattern #{pattern}."
      end

      @overledger_transaction_id = overledger_transaction_id
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if !type.nil? && type.to_s.length > 50
        fail ArgumentError, 'invalid value for "type", the character length must be smaller than or equal to 50.'
      end

      if !type.nil? && type.to_s.length < 0
        fail ArgumentError, 'invalid value for "type", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9-_ ]{1,50}$/)
      if !type.nil? && type !~ pattern
        fail ArgumentError, "invalid value for \"type\", must conform to the pattern #{pattern}."
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] transaction_id Value to be assigned
    def transaction_id=(transaction_id)
      if !transaction_id.nil? && transaction_id.to_s.length > 100
        fail ArgumentError, 'invalid value for "transaction_id", the character length must be smaller than or equal to 100.'
      end

      if !transaction_id.nil? && transaction_id.to_s.length < 0
        fail ArgumentError, 'invalid value for "transaction_id", the character length must be great than or equal to 0.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9-]{1,100}$/)
      if !transaction_id.nil? && transaction_id !~ pattern
        fail ArgumentError, "invalid value for \"transaction_id\", must conform to the pattern #{pattern}."
      end

      @transaction_id = transaction_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          client_id == o.client_id &&
          request_id == o.request_id &&
          overledger_transaction_id == o.overledger_transaction_id &&
          location == o.location &&
          transaction_history == o.transaction_history &&
          type == o.type &&
          transaction_id == o.transaction_id &&
          status == o.status
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [client_id, request_id, overledger_transaction_id, location, transaction_history, type, transaction_id, status].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
